### ISSUE TITLE
Integer values from GCP exceed the MAX value of an Integer in Hive

### ISSUE THREAD

**Issue by andrispalfi** [HotelsDotCom/circus-train-bigquery#19]
We have several integer values in GCP (costs, ids) which exceed the possible MAX value of the Integer in Hive. Circus Train keeps the Integer type in the Hive schemas of the migrated tables and it ignores that the maximum value for an Integer in Hive is 2,147,483,647 as it stores integers in 4 bytes.
We receive NULL in Hive upon exceeding the MAX. It would be better to use bigint in these cases.

**Comment by AnanaMJ** [comment]
Can you give an example of the values? I can test if the current pull request would address this issue.

**Comment by andrispalfi** [comment]
For example, performing this query:
"select distinct cost from {our table} where cost > 2147483647"
I receive values like: 3018180000, 14656570000, 5140290000 and so on. (cost type is Integer in GCP)
Performing the same query on the migrated table I receive an empty result set.

**Comment by AnanaMJ** [comment]
I've just tested it with version 3.0.0 (the latest version released) and I'm getting the right values. Are you using a different version?

**Comment by andrispalfi** [comment]
I am using 2.0.2. Then I am going to try it with the latest one.

**Comment by AnanaMJ** [comment]
Ok, let me know how it goes and if there are any other issues on the way. If there are, you can also slack me for a quicker response.

**Comment by andrispalfi** [comment]
Sure. Thanks @AnanaMJ !

**Comment by AnanaMJ** [comment]
@andrispalfi Have you encountered this issue in the new version of Circus Train BigQuery? If not, let me know if you're happy with this issue being closed.

**Comment by AnanaMJ** [comment]
This issue is fixed in the new version.
