### ISSUE TITLE
Partition column gets duplicated while replicating a partitioned  GCP-BQ table to AWS-hive.

### ISSUE THREAD

**Issue by ankitsingh27991** [HotelsDotCom/circus-train-bigquery#37]
Hi Team, 

I have used the following copier options (code snippet below) in my YAML config.

`copier-options:
    circustrain-bigquery-partition-by: partition_date
    circustrain-bigquery-partition-filter: partition_date BETWEEN DATE_SUB(current_date(), INTERVAL 2 MONTH) AND CURRENT_DATE()`

The replication is generally successful but the resultant table has two issues:

1. There is an extra regular column with the same name as the partition column.
2. The data is getting inserted to the extra column and not the partition column, the partitioned column is getting inserted with nulls.

Please let me know if you need any other details or logs to debug this, and I will send the details privately.

**Comment by ankitsingh27991** [comment]
#2 - Only arises when the partition column is somewhere at the middle of the column list not and not at the very end.

**Comment by JayGreeeen** [comment]
Thanks for bringing this up, it has now been fixed by #38 and will be available in the next release.
